version: '3.7'
services:
  pihole:
    image: pihole/pihole:4.3.2-1
    container_name: pihole
    #    domainname: local
    dns:
      - 127.0.0.1
      - 1.1.1.1
    volumes:
      - "config:/etc/pihole/"
      - "dnsmasq:/etc/dnsmasq.d/"  
    restart: unless-stopped
    networks:
      - web
    ports:
      - '0.0.0.0:53:53/tcp'
      - '0.0.0.0:53:53/udp'
      - '0.0.0.0:67:67/udp'
    expose:
      - 80
      - 443
    environment: 
      TZ: UTC
      ServerIP: n.n.n.n 
      WEBPASSWORD: SuperSecurePasshrase
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: pihole.domain.co.uk
      VIRTUAL_PORT: 80      
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.pihole.rule=Host(`pihole.domain.co.uk`)"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.tls.certresolver=le_dns"

networks:
  web:
    external: true

volumes:
  config:
  dnsmasq:
