name: pihole
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    ports:
      - 53/tcp
      - 53/udp
      - 67/udp # Only required if you are using Pi-hole as your DHCP server
      - 80/tcp
    networks:
      user-vlan:
        ipv4_address: ${USER_VLAN_IP}
        mac_address: ${USER_VLAN_MAC}
      iot-vlan:
        ipv4_address: ${IOT_VLAN_IP}
        mac_address: ${IOT_VLAN_MAC}
      cctv-vlan:
        ipv4_address: ${CCTV_VLAN_IP}
        mac_address: ${CCTV_VLAN_MAC}
      proxy-vlan:
        ipv4_address: ${PROXY_VLAN_IP}
        mac_address: ${PROXY_VLAN_MAC}
      system-vlan:
        ipv4_address: ${SYSTEM_VLAN_IP}
        mac_address: ${SYSTEM_VLAN_MAC}
    environment:
      TZ: UTC
      WEBPASSWORD: ${WEBPASSWORD}
      PIHOLE_DNS_: 9.9.9.9;149.112.112.112
      ServerIP: ${SYSTEM_VLAN_IP}
      FTLCONF_REPLY_ADDR4: ${SYSTEM_VLAN_IP}
      VIRTUAL_HOST: pihole.${DOMAIN}
      DHCP_ACTIVE: "true"
      DHCP_START: ${DHCP_START}
      DHCP_END: 1${DHCP_END}
      DHCP_ROUTER: 1${DHCP_ROUTER}
      PIHOLE_DOMAIN: ${DOMAIN}
    # Volumes store your data between container upgrades
    volumes:
      - /u/pihole/etc-pihole:/etc/pihole
      - /u/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy-vlan
      - traefik.http.routers.pihole.rule=Host(`pihole.${DOMAIN}`)
      - traefik.http.services.pihole.loadbalancer.server.port=80
      - traefik.http.routers.pihole.entrypoints=websecure
      - traefik.http.routers.pihole.tls.certresolver=le_dns
    
##############################

networks:
  user-vlan:
    external: true
  iot-vlan:
    external: true
  cctv-vlan:
    external: true
  proxy-vlan:
    external: true
  system-vlan:
    external: true

# volumes:
#   config:
#   dnsmasq:
#   tftp:
#   data:  
